In [2]:
import pandas as pd
import numpy as np
import joblib
from itertools import product

# Load the trained model
model = joblib.load('random_forest_model.pkl')

# Define the values for the combinations
academic_programs = np.arange(179)  # Assuming the programs are indexed from 0 to 178
seats = np.arange(5)  # Seat values from 0 to 4
institutes = np.arange(23)  # Institute values from 0 to 22
years = [2025, 2026]  # Future years

# Prepare all possible combinations of the input columns
combinations = list(product(institutes, years, academic_programs, seats))

# Initialize an empty list to store the results
results = []

# Loop through each combination and predict
for inst, year, prog, seat in combinations:
    # Prepare the input data for the model
    X_input = pd.DataFrame({
        'Institute': [inst],
        'Gender': [0],  # Assuming Gender = 0 for simplicity, or loop for all values of Gender if needed
        'Year': [year],
        'Academic_Program_Name': [prog],
        'Seat': [seat],
        'Disability': [0]  # Assuming Disability = 0 for simplicity, or loop for all values of Disability if needed
    })
    
    # Make predictions
    prediction = model.predict(X_input)
    print(prediction)
    # Store the combination and prediction results
    results.append({
        'Institute': inst,
        'Gender': 0,  # Gender can be adjusted if needed
        'Year': year,
        'Academic_Program_Name': prog,
        'Seat': seat,
        'Disability': 0,  # Disability can be adjusted if needed
        'Closing_Rank': prediction[0][0],  # Closing Rank prediction
        'Opening_Rank': prediction[0][1]   # Opening Rank prediction
    })

# Convert the results to a DataFrame
results_df = pd.DataFrame(results)

# Save the results to a CSV file
results_df.to_csv('future_predictions_2025_2026.csv', index=False)

print("Predictions saved to 'future_predictions_2025_2026.csv'")


[[755.96 603.15]]
[[3837.99 3047.74]]
[[10416.37  7714.85]]
[[2174.18 1852.96]]
[[1782.55 1537.11]]
[[722.16 607.32]]
[[5106.21 4088.95]]
[[14239.33  9496.95]]
[[2492.68 2239.22]]
[[2301.76 2074.2 ]]
[[305.08 205.96]]
[[1266.44  809.08]]
[[3962.63 2481.49]]
[[564.95 358.56]]
[[434.77 376.1 ]]
[[305.08 205.96]]
[[2072.75 1212.62]]
[[4021.6  2537.97]]
[[1123.81  689.55]]
[[808.87 563.82]]
[[794.31 692.51]]
[[2198.93 1234.56]]
[[4112.3  2591.23]]
[[1115.64  814.59]]
[[900.28 601.29]]
[[239.92 182.81]]
[[1051.87  658.5 ]]
[[3903.99 2462.98]]
[[269.58 146.45]]
[[177.66 122.36]]
[[627.14 404.47]]
[[2039.4  1057.66]]
[[4083.84 2599.21]]
[[1181.12  742.84]]
[[718.46 544.99]]
[[640.97 414.8 ]]
[[2423.06 1478.27]]
[[6962.   4837.97]]
[[1346.5  915.9]]
[[847.35 668.23]]
[[648.75 392.74]]
[[2587.37 1615.9 ]]
[[6981.17 4852.2 ]]
[[1432.49  974.64]]
[[984.18 846.15]]
[[564.13 317.36]]
[[1947.01 1379.99]]
[[7247.96 5065.5 ]]
[[842.32 486.12]]
[[638.7  420.97]]
[[764.84 667.45]]
[[2829.47 2176.62]]
[[